//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kadri
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Анкеты.
    /// </summary>
    // *** Start programmer edit section *** (Анкеты CustomAttributes)

    // *** End programmer edit section *** (Анкеты CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("АнкетыE", new string[] {
            "ID as \'ID\'",
            "ФИО as \'ФИО\'",
            "Контакты as \'Контакты\'",
            "Образование as \'Образование\'",
            "Опыт_работы as \'Опыт_работы\'",
            "ЛК as \'ЛК\'",
            "Вакансия as \'Вакансия\'",
            "Вакансия.Название as \'Название\'"}, Hidden=new string[] {
            "Вакансия.Название"})]
    [MasterViewDefineAttribute("АнкетыE", "Вакансия", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    [View("АнкетыL", new string[] {
            "ID as \'ID\'",
            "ФИО as \'ФИО\'",
            "Контакты as \'Контакты\'",
            "Образование as \'Образование\'",
            "Опыт_работы as \'Опыт_работы\'",
            "ЛК as \'ЛК\'",
            "Вакансия.Название as \'Название\'"})]
    public class Анкеты : ICSSoft.STORMNET.DataObject
    {
        
        private int fID;
        
        private string fФИО;
        
        private string fОбразование;
        
        private string fКонтакты;
        
        private string fОпыт_работы;
        
        private string fЛК;
        
        private IIS.Kadri.Должности fВакансия;
        
        // *** Start programmer edit section *** (Анкеты CustomMembers)

        // *** End programmer edit section *** (Анкеты CustomMembers)

        
        /// <summary>
        /// ID.
        /// </summary>
        // *** Start programmer edit section *** (Анкеты.ID CustomAttributes)

        // *** End programmer edit section *** (Анкеты.ID CustomAttributes)
        [NotNull()]
        public virtual int ID
        {
            get
            {
                // *** Start programmer edit section *** (Анкеты.ID Get start)

                // *** End programmer edit section *** (Анкеты.ID Get start)
                int result = this.fID;
                // *** Start programmer edit section *** (Анкеты.ID Get end)

                // *** End programmer edit section *** (Анкеты.ID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкеты.ID Set start)

                // *** End programmer edit section *** (Анкеты.ID Set start)
                this.fID = value;
                // *** Start programmer edit section *** (Анкеты.ID Set end)

                // *** End programmer edit section *** (Анкеты.ID Set end)
            }
        }
        
        /// <summary>
        /// Контакты.
        /// </summary>
        // *** Start programmer edit section *** (Анкеты.Контакты CustomAttributes)

        // *** End programmer edit section *** (Анкеты.Контакты CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Контакты
        {
            get
            {
                // *** Start programmer edit section *** (Анкеты.Контакты Get start)

                // *** End programmer edit section *** (Анкеты.Контакты Get start)
                string result = this.fКонтакты;
                // *** Start programmer edit section *** (Анкеты.Контакты Get end)

                // *** End programmer edit section *** (Анкеты.Контакты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкеты.Контакты Set start)

                // *** End programmer edit section *** (Анкеты.Контакты Set start)
                this.fКонтакты = value;
                // *** Start programmer edit section *** (Анкеты.Контакты Set end)

                // *** End programmer edit section *** (Анкеты.Контакты Set end)
            }
        }
        
        /// <summary>
        /// ЛК.
        /// </summary>
        // *** Start programmer edit section *** (Анкеты.ЛК CustomAttributes)

        // *** End programmer edit section *** (Анкеты.ЛК CustomAttributes)
        [StrLen(255)]
        public virtual string ЛК
        {
            get
            {
                // *** Start programmer edit section *** (Анкеты.ЛК Get start)

                // *** End programmer edit section *** (Анкеты.ЛК Get start)
                string result = this.fЛК;
                // *** Start programmer edit section *** (Анкеты.ЛК Get end)

                // *** End programmer edit section *** (Анкеты.ЛК Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкеты.ЛК Set start)

                // *** End programmer edit section *** (Анкеты.ЛК Set start)
                this.fЛК = value;
                // *** Start programmer edit section *** (Анкеты.ЛК Set end)

                // *** End programmer edit section *** (Анкеты.ЛК Set end)
            }
        }
        
        /// <summary>
        /// Образование.
        /// </summary>
        // *** Start programmer edit section *** (Анкеты.Образование CustomAttributes)

        // *** End programmer edit section *** (Анкеты.Образование CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Образование
        {
            get
            {
                // *** Start programmer edit section *** (Анкеты.Образование Get start)

                // *** End programmer edit section *** (Анкеты.Образование Get start)
                string result = this.fОбразование;
                // *** Start programmer edit section *** (Анкеты.Образование Get end)

                // *** End programmer edit section *** (Анкеты.Образование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкеты.Образование Set start)

                // *** End programmer edit section *** (Анкеты.Образование Set start)
                this.fОбразование = value;
                // *** Start programmer edit section *** (Анкеты.Образование Set end)

                // *** End programmer edit section *** (Анкеты.Образование Set end)
            }
        }
        
        /// <summary>
        /// Опыт_работы.
        /// </summary>
        // *** Start programmer edit section *** (Анкеты.Опыт_работы CustomAttributes)

        // *** End programmer edit section *** (Анкеты.Опыт_работы CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Опыт_работы
        {
            get
            {
                // *** Start programmer edit section *** (Анкеты.Опыт_работы Get start)

                // *** End programmer edit section *** (Анкеты.Опыт_работы Get start)
                string result = this.fОпыт_работы;
                // *** Start programmer edit section *** (Анкеты.Опыт_работы Get end)

                // *** End programmer edit section *** (Анкеты.Опыт_работы Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкеты.Опыт_работы Set start)

                // *** End programmer edit section *** (Анкеты.Опыт_работы Set start)
                this.fОпыт_работы = value;
                // *** Start programmer edit section *** (Анкеты.Опыт_работы Set end)

                // *** End programmer edit section *** (Анкеты.Опыт_работы Set end)
            }
        }
        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Анкеты.ФИО CustomAttributes)

        // *** End programmer edit section *** (Анкеты.ФИО CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Анкеты.ФИО Get start)

                // *** End programmer edit section *** (Анкеты.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Анкеты.ФИО Get end)

                // *** End programmer edit section *** (Анкеты.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкеты.ФИО Set start)

                // *** End programmer edit section *** (Анкеты.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Анкеты.ФИО Set end)

                // *** End programmer edit section *** (Анкеты.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Анкеты.
        /// </summary>
        // *** Start programmer edit section *** (Анкеты.Вакансия CustomAttributes)

        // *** End programmer edit section *** (Анкеты.Вакансия CustomAttributes)
        [PropertyStorage(new string[] {
                "Вакансия"})]
        [NotNull()]
        public virtual IIS.Kadri.Должности Вакансия
        {
            get
            {
                // *** Start programmer edit section *** (Анкеты.Вакансия Get start)

                // *** End programmer edit section *** (Анкеты.Вакансия Get start)
                IIS.Kadri.Должности result = this.fВакансия;
                // *** Start programmer edit section *** (Анкеты.Вакансия Get end)

                // *** End programmer edit section *** (Анкеты.Вакансия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкеты.Вакансия Set start)

                // *** End programmer edit section *** (Анкеты.Вакансия Set start)
                this.fВакансия = value;
                // *** Start programmer edit section *** (Анкеты.Вакансия Set end)

                // *** End programmer edit section *** (Анкеты.Вакансия Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "АнкетыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АнкетыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АнкетыE", typeof(IIS.Kadri.Анкеты));
                }
            }
            
            /// <summary>
            /// "АнкетыL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АнкетыL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АнкетыL", typeof(IIS.Kadri.Анкеты));
                }
            }
        }
    }
}
