//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kadri
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Должности.
    /// </summary>
    // *** Start programmer edit section *** (Должности CustomAttributes)

    // *** End programmer edit section *** (Должности CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДолжностиE", new string[] {
            "ID as \'ID\'",
            "Название as \'Название\'",
            "Оклад as \'Оклад\'"})]
    [View("ДолжностиL", new string[] {
            "ID as \'ID\'",
            "Название as \'Название\'",
            "Оклад as \'Оклад\'"})]
    public class Должности : ICSSoft.STORMNET.DataObject
    {
        
        private int fID;
        
        private string fНазвание;
        
        private int fОклад;
        
        // *** Start programmer edit section *** (Должности CustomMembers)

        // *** End programmer edit section *** (Должности CustomMembers)

        
        /// <summary>
        /// ID.
        /// </summary>
        // *** Start programmer edit section *** (Должности.ID CustomAttributes)

        // *** End programmer edit section *** (Должности.ID CustomAttributes)
        [NotNull()]
        public virtual int ID
        {
            get
            {
                // *** Start programmer edit section *** (Должности.ID Get start)

                // *** End programmer edit section *** (Должности.ID Get start)
                int result = this.fID;
                // *** Start programmer edit section *** (Должности.ID Get end)

                // *** End programmer edit section *** (Должности.ID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Должности.ID Set start)

                // *** End programmer edit section *** (Должности.ID Set start)
                this.fID = value;
                // *** Start programmer edit section *** (Должности.ID Set end)

                // *** End programmer edit section *** (Должности.ID Set end)
            }
        }
        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Должности.Название CustomAttributes)

        // *** End programmer edit section *** (Должности.Название CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (Должности.Название Get start)

                // *** End programmer edit section *** (Должности.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (Должности.Название Get end)

                // *** End programmer edit section *** (Должности.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Должности.Название Set start)

                // *** End programmer edit section *** (Должности.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (Должности.Название Set end)

                // *** End programmer edit section *** (Должности.Название Set end)
            }
        }
        
        /// <summary>
        /// Оклад.
        /// </summary>
        // *** Start programmer edit section *** (Должности.Оклад CustomAttributes)

        // *** End programmer edit section *** (Должности.Оклад CustomAttributes)
        [NotNull()]
        public virtual int Оклад
        {
            get
            {
                // *** Start programmer edit section *** (Должности.Оклад Get start)

                // *** End programmer edit section *** (Должности.Оклад Get start)
                int result = this.fОклад;
                // *** Start programmer edit section *** (Должности.Оклад Get end)

                // *** End programmer edit section *** (Должности.Оклад Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Должности.Оклад Set start)

                // *** End programmer edit section *** (Должности.Оклад Set start)
                this.fОклад = value;
                // *** Start programmer edit section *** (Должности.Оклад Set end)

                // *** End programmer edit section *** (Должности.Оклад Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДолжностиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДолжностиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДолжностиE", typeof(IIS.Kadri.Должности));
                }
            }
            
            /// <summary>
            /// "ДолжностиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДолжностиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДолжностиL", typeof(IIS.Kadri.Должности));
                }
            }
        }
    }
}
