//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kadri
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Контроль_ ТЗ.
    /// </summary>
    // *** Start programmer edit section *** (Контроль_ТЗ CustomAttributes)

    // *** End programmer edit section *** (Контроль_ТЗ CustomAttributes)
    [AutoAltered()]
    [Caption("Контроль_ ТЗ")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("Контроль_ТЗE", new string[] {
            "ID as \'ID\'",
            "Дата_проверки as \'Дата_проверки\'"})]
    [AssociatedDetailViewAttribute("Контроль_ТЗE", "Проверяемые", "ПроверяемыеE", true, "", "Проверяемые", true, new string[] {
            ""})]
    [View("Контроль_ТЗL", new string[] {
            "ID as \'ID\'",
            "Дата_проверки as \'Дата_проверки\'"})]
    public class Контроль_ТЗ : ICSSoft.STORMNET.DataObject
    {
        
        private int fID;
        
        private System.DateTime fДата_проверки;
        
        private IIS.Kadri.DetailArrayOfПроверяемые fПроверяемые;
        
        // *** Start programmer edit section *** (Контроль_ТЗ CustomMembers)

        // *** End programmer edit section *** (Контроль_ТЗ CustomMembers)

        
        /// <summary>
        /// ID.
        /// </summary>
        // *** Start programmer edit section *** (Контроль_ТЗ.ID CustomAttributes)

        // *** End programmer edit section *** (Контроль_ТЗ.ID CustomAttributes)
        [NotNull()]
        public virtual int ID
        {
            get
            {
                // *** Start programmer edit section *** (Контроль_ТЗ.ID Get start)

                // *** End programmer edit section *** (Контроль_ТЗ.ID Get start)
                int result = this.fID;
                // *** Start programmer edit section *** (Контроль_ТЗ.ID Get end)

                // *** End programmer edit section *** (Контроль_ТЗ.ID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Контроль_ТЗ.ID Set start)

                // *** End programmer edit section *** (Контроль_ТЗ.ID Set start)
                this.fID = value;
                // *** Start programmer edit section *** (Контроль_ТЗ.ID Set end)

                // *** End programmer edit section *** (Контроль_ТЗ.ID Set end)
            }
        }
        
        /// <summary>
        /// Дата_проверки.
        /// </summary>
        // *** Start programmer edit section *** (Контроль_ТЗ.Дата_проверки CustomAttributes)

        // *** End programmer edit section *** (Контроль_ТЗ.Дата_проверки CustomAttributes)
        [NotNull()]
        public virtual System.DateTime Дата_проверки
        {
            get
            {
                // *** Start programmer edit section *** (Контроль_ТЗ.Дата_проверки Get start)

                // *** End programmer edit section *** (Контроль_ТЗ.Дата_проверки Get start)
                System.DateTime result = this.fДата_проверки;
                // *** Start programmer edit section *** (Контроль_ТЗ.Дата_проверки Get end)

                // *** End programmer edit section *** (Контроль_ТЗ.Дата_проверки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Контроль_ТЗ.Дата_проверки Set start)

                // *** End programmer edit section *** (Контроль_ТЗ.Дата_проверки Set start)
                this.fДата_проверки = value;
                // *** Start programmer edit section *** (Контроль_ТЗ.Дата_проверки Set end)

                // *** End programmer edit section *** (Контроль_ТЗ.Дата_проверки Set end)
            }
        }
        
        /// <summary>
        /// Контроль_ ТЗ.
        /// </summary>
        // *** Start programmer edit section *** (Контроль_ТЗ.Проверяемые CustomAttributes)

        // *** End programmer edit section *** (Контроль_ТЗ.Проверяемые CustomAttributes)
        public virtual IIS.Kadri.DetailArrayOfПроверяемые Проверяемые
        {
            get
            {
                // *** Start programmer edit section *** (Контроль_ТЗ.Проверяемые Get start)

                // *** End programmer edit section *** (Контроль_ТЗ.Проверяемые Get start)
                if ((this.fПроверяемые == null))
                {
                    this.fПроверяемые = new IIS.Kadri.DetailArrayOfПроверяемые(this);
                }
                IIS.Kadri.DetailArrayOfПроверяемые result = this.fПроверяемые;
                // *** Start programmer edit section *** (Контроль_ТЗ.Проверяемые Get end)

                // *** End programmer edit section *** (Контроль_ТЗ.Проверяемые Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Контроль_ТЗ.Проверяемые Set start)

                // *** End programmer edit section *** (Контроль_ТЗ.Проверяемые Set start)
                this.fПроверяемые = value;
                // *** Start programmer edit section *** (Контроль_ТЗ.Проверяемые Set end)

                // *** End programmer edit section *** (Контроль_ТЗ.Проверяемые Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "Контроль_ТЗE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Контроль_ТЗE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Контроль_ТЗE", typeof(IIS.Kadri.Контроль_ТЗ));
                }
            }
            
            /// <summary>
            /// "Контроль_ТЗL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Контроль_ТЗL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Контроль_ТЗL", typeof(IIS.Kadri.Контроль_ТЗ));
                }
            }
        }
    }
}
