//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kadri
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Проверяемые.
    /// </summary>
    // *** Start programmer edit section *** (Проверяемые CustomAttributes)

    // *** End programmer edit section *** (Проверяемые CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПроверяемыеE", new string[] {
            "Результат as \'Результат\'",
            "Сотрудник as \'Сотрудник\'",
            "Сотрудник.ФИО as \'ФИО\'"}, Hidden=new string[] {
            "Сотрудник.ФИО"})]
    [MasterViewDefineAttribute("ПроверяемыеE", "Сотрудник", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    public class Проверяемые : ICSSoft.STORMNET.DataObject
    {
        
        private string fРезультат;
        
        private IIS.Kadri.Сотрудники fСотрудник;
        
        private IIS.Kadri.Контроль_ТЗ fКонтроль_ТЗ;
        
        // *** Start programmer edit section *** (Проверяемые CustomMembers)

        // *** End programmer edit section *** (Проверяемые CustomMembers)

        
        /// <summary>
        /// Результат.
        /// </summary>
        // *** Start programmer edit section *** (Проверяемые.Результат CustomAttributes)

        // *** End programmer edit section *** (Проверяемые.Результат CustomAttributes)
        [StrLen(255)]
        public virtual string Результат
        {
            get
            {
                // *** Start programmer edit section *** (Проверяемые.Результат Get start)

                // *** End programmer edit section *** (Проверяемые.Результат Get start)
                string result = this.fРезультат;
                // *** Start programmer edit section *** (Проверяемые.Результат Get end)

                // *** End programmer edit section *** (Проверяемые.Результат Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Проверяемые.Результат Set start)

                // *** End programmer edit section *** (Проверяемые.Результат Set start)
                this.fРезультат = value;
                // *** Start programmer edit section *** (Проверяемые.Результат Set end)

                // *** End programmer edit section *** (Проверяемые.Результат Set end)
            }
        }
        
        /// <summary>
        /// Проверяемые.
        /// </summary>
        // *** Start programmer edit section *** (Проверяемые.Сотрудник CustomAttributes)

        // *** End programmer edit section *** (Проверяемые.Сотрудник CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудник"})]
        [NotNull()]
        public virtual IIS.Kadri.Сотрудники Сотрудник
        {
            get
            {
                // *** Start programmer edit section *** (Проверяемые.Сотрудник Get start)

                // *** End programmer edit section *** (Проверяемые.Сотрудник Get start)
                IIS.Kadri.Сотрудники result = this.fСотрудник;
                // *** Start programmer edit section *** (Проверяемые.Сотрудник Get end)

                // *** End programmer edit section *** (Проверяемые.Сотрудник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Проверяемые.Сотрудник Set start)

                // *** End programmer edit section *** (Проверяемые.Сотрудник Set start)
                this.fСотрудник = value;
                // *** Start programmer edit section *** (Проверяемые.Сотрудник Set end)

                // *** End programmer edit section *** (Проверяемые.Сотрудник Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Kadri.Контроль_ТЗ.
        /// </summary>
        // *** Start programmer edit section *** (Проверяемые.Контроль_ТЗ CustomAttributes)

        // *** End programmer edit section *** (Проверяемые.Контроль_ТЗ CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Контроль_ТЗ"})]
        public virtual IIS.Kadri.Контроль_ТЗ Контроль_ТЗ
        {
            get
            {
                // *** Start programmer edit section *** (Проверяемые.Контроль_ТЗ Get start)

                // *** End programmer edit section *** (Проверяемые.Контроль_ТЗ Get start)
                IIS.Kadri.Контроль_ТЗ result = this.fКонтроль_ТЗ;
                // *** Start programmer edit section *** (Проверяемые.Контроль_ТЗ Get end)

                // *** End programmer edit section *** (Проверяемые.Контроль_ТЗ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Проверяемые.Контроль_ТЗ Set start)

                // *** End programmer edit section *** (Проверяемые.Контроль_ТЗ Set start)
                this.fКонтроль_ТЗ = value;
                // *** Start programmer edit section *** (Проверяемые.Контроль_ТЗ Set end)

                // *** End programmer edit section *** (Проверяемые.Контроль_ТЗ Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПроверяемыеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПроверяемыеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПроверяемыеE", typeof(IIS.Kadri.Проверяемые));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Проверяемые.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfПроверяемые CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfПроверяемые CustomAttributes)
    public class DetailArrayOfПроверяемые : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Kadri.DetailArrayOfПроверяемые members)

        // *** End programmer edit section *** (IIS.Kadri.DetailArrayOfПроверяемые members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Проверяемые by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Проверяемые.
        /// </summary>
        public DetailArrayOfПроверяемые(IIS.Kadri.Контроль_ТЗ fКонтроль_ТЗ) : 
                base(typeof(Проверяемые), ((ICSSoft.STORMNET.DataObject)(fКонтроль_ТЗ)))
        {
        }
        
        public IIS.Kadri.Проверяемые this[int index]
        {
            get
            {
                return ((IIS.Kadri.Проверяемые)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Kadri.Проверяемые dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
